# Site settings
title: Science Viking Labs
email: justin.m.basinger@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Growing beards and automating the world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sciencevikinglabs.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  ScienceVikings

# Build settings
markdown: kramdown

highlighter:      rouge