# Site settings
description: "Beards and Code."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.sciencevikinglabs.com" # the base hostname & protocol for your site
title: "The Science Viking Labs Blog"

# User settings
username: Science Viking Labs
user_description: Anon Developer at Lorem Ipsum Dolor
user_title: Science Viking Labs
email: ScienceVikingLabs@Gmail.com
twitter_username: ScienceVikings
github_username:  ScienceVikings
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum
author: {'Justin': {'description': 'Hybrid/Mobile Developer, Beard Enthusiast','email': 'Justin.M.Basinger@Gmail.com','image': '/assets/img/Justin.jpeg','name': 'Justin Basinger'},
         'Ryan': {'description': 'Security Researcher, Software Developer, Beer Enthusiast','email': 'BoutotR@Gmail.com','image': '/assets/img/Ryan.jpg','name': 'Ryan Boutot'}}

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  # - title: Series
  #   url: /series
  # - title: Tags
  #   url: /tags
  # - title: About Me
  #   url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
